# Generated by Django 5.1.6 on 2026-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
