# Generated by Django 5.1.6 on 2026-08-01 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.RemoveField(
            model_name='ngoprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='medicinedonation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicinedonation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicinedonation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medicinerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='medicinedonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinedonation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicinedonation'),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='NGOProfile',
        ),
    ]
