# Generated by Django 5.1.6 on 2026-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_donation_remove_ngoprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
    ]
