# Generated by Django 5.1.6 on 2026-08-02 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicinedonation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerequest',
            name='is_urgent',
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedonation',
            name='medicine_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicinedonation',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicinedonation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DONOR', 'Donor'), ('NGO', 'NGO')], default='DONOR', max_length=10),
        ),
    ]
